# Generated by Django 4.2.7 on 2024-01-29 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_customer', to='main.customer'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='main.product'),
        ),
    ]
